id: P009282
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:31:27.556774
source_metadata:
  id: bdr:W1CZ898
  title: བརྒལ་ལན་ལེགས་པའི་གཏམ་འབྱེད
  author: ''
  volumes:
    7d64a6b01ce74017b172ca85011f61b9:
      image_group_id: I1CZ1054
      title: ''
      volume_number: 1
      total_pages: 60
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
