id: P009282
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ898
  title: བརྒལ་ལན་ལེགས་པའི་གཏམ་འབྱེད
  author: ''
  volumes:
    7d64a6b01ce74017b172ca85011f61b9:
      image_group_id: I1CZ1054
      title: ''
      volume_number: 1
      total_pages: 60
      base_file: v001.txt
