id: I1704B8EB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:57:22+00:00'
last_modified: '2022-06-08T09:54:37.980163+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ898
  title: བརྒལ་ལན་ལེགས་པའི་གཏམ་འབྱེད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4811':
      image_group_id: I1CZ1054
      title: ''
      total_pages: 60
      order: 1
      base_file: 4811.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
